# -*- coding: utf-8 -*-
'''
# doc generated by chatgpt
the given code is a Python script that creates an image using numpy and matplotlib and allows the user to click on the image to print the x and y coordinates of the click. Here is a line by line breakdown of the code along with comments:
    
The numpy module is used to create a 2D array img of zeros with a shape of (10, 12) and of type np.uint8. A portion of the array is then set to ones by selecting a slice of the array with indices 2:8 along the first axis and 3:9 along the second axis.

The matplotlib module is used to display the image. The imshow function is used to display the image in a plot. The plot is stored in the variable im.

The mpl_connect method is used to connect the onclick function to the plot. This means that when the user clicks on the plot, the onclick function will be called.

Finally, the show function is called to display the plot. The block parameter is set to True, which means that the script will block until the plot window is closed.

After the plot is closed, the x and y coordinates of the last click are printed using the print function. Note that x and y are defined inside the onclick function as global variables so that they can be accessed outside the function.
'''

import numpy as np
import matplotlib
import cv2
import matplotlib.pyplot as plt
matplotlib.use('TkAgg')

point_list=[]

img = cv2.imread('img2.jpg', 0)
# click and seed point set up
x = None
y = None

kernel1 = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3)) #cv2.MORPH_RECT for all 1s
#print(kernel1)



# The mouse coordinate system and the Matplotlib coordinate system are different, handle that
def onclick(event):
    global x, y
    ax = event.inaxes
    if ax is not None:
        x, y = ax.transData.inverted().transform([event.x, event.y])
        x = int(round(x))
        y = int(round(y))
        print('button=%d, x=%d, y=%d, xdata=%f, ydata=%f' %
              (event.button, event.x, event.y, x, y))
        point_list.append((x,y))
        print(x,y)
        # hole Filling :)
        emptyImg = np.zeros(img.shape,dtype='uint8')
        emptyImg_ = np.zeros(img.shape,dtype='uint8')
        output = np.zeros(img.shape,dtype='uint8')
        emptyImg[y][x] = 255
        cv2.imshow("gg", emptyImg)
        
        while(1):
            
            emptyImg_ = emptyImg
            
            emptyImg = cv2.dilate(emptyImg,kernel1,iterations = 1)
            img_ = cv2.bitwise_not(img)
            emptyImg = cv2.bitwise_and(img_,emptyImg)
            x = np.array_equal(emptyImg_ , emptyImg)
            output = cv2.bitwise_or(emptyImg,img)
            cv2.imshow("test", emptyImg)
            cv2.waitKey(0)
            print(x)
            if ( x == True):
                break
            
        output = cv2.bitwise_or(emptyImg,img)
        cv2.imshow("output", output)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

        
        
         
 

      


X = np.zeros_like(img)
plt.title("Please select seed pixel from the input")
im = plt.imshow(img, cmap='gray')
im.figure.canvas.mpl_connect('button_press_event', onclick)
plt.show(block=True)

print(point_list)
